export function calculate () {
  /* global P */
  const AGONY_RESISTANCE_PRECISION = P.AGONY_RESISTANCE * (P.AGONY_CHANNELER + P
    .RECURSIVE_RESOURCING + P.MISTLOCK_SINGULARITIES) / 100 * P
    .INFINITE_MIST_OMNIPOTION;
  const EQUIPMENT = P.AMULET_SLOT + P.BACK_SLOT + P.BEAR_TRINKET_SLOT + P
    .CHEST_SLOT + P.CUBE_TRINKET_SLOT + P.FEET_SLOT + P.HAND_SLOT + P
    .HEAD_SLOT + P.LEFT_RING_SLOT + P.LEG_SLOT + P.RIGHT_RING_SLOT + P
    .SHIELD_SLOT + P.SHOULDER_SLOT + P.SWORD_SLOT;
  const TRAIT_RANGER_PRECISION = P.SPOTTER;
  const TRAIT_THIEF_PRECISION = P.BE_QUICK_OR_BE_KILLED + P.SILENT_SCOPE;
  const TRAIT_ELEMENTALIST_PRECISION = P.ELEMENTS_OF_RAGE * P.VITALITY;
  const TRAIT_NECROMANCER_PRECISION = P.FURIOUS_DEMISE;
  const TRAIT_GUARDIAN_PRECISION = P.RIGHT_HAND_STRENGTH;
  const UTILITY_SKILL = (P.DOUBLED_STANDARDS + 1) * P.BANNER_OF_DISCIPLINE + P
    .CONJURE_LIGHTNING_HAMMER + P.SIGNET_OF_AGILITY + P.SIGNET_OF_FIRE + P
    .SIGNET_OF_FURY;
  const PRECISION = 1000 + AGONY_RESISTANCE_PRECISION + EQUIPMENT +
    TRAIT_RANGER_PRECISION + TRAIT_THIEF_PRECISION +
    TRAIT_ELEMENTALIST_PRECISION + TRAIT_NECROMANCER_PRECISION +
    TRAIT_GUARDIAN_PRECISION + UTILITY_SKILL;
  /* global demoStart */
  demoStart(parseInt(document.getElementById('P.PRECISION').innerText.replace(
    ',', '')), 0, '', '', 'P.PRECISION', PRECISION);
  const BUFF = P.FURY * 20;
  const SIGIL_OF_ACCURACY = P.MAJOR_SIGIL_OF_ACCURACY + P
    .MINOR_SIGIL_OF_ACCURACY + P.SUPERIOR_SIGIL_OF_ACCURACY;
  const TRAIT_ENGINEER_CRITICAL_CHANCE = P.HEMATIC_FOCUS * P.BLEEDING + P
    .HIGH_CALIBER;
  const TRAIT_RANGER_CRITICAL_CHANCE = P.HUNTERS_TACTICS + P.VICIOUS_QUARRY * P
    .FURY;
  const TRAIT_THIEF_CRITICAL_CHANCE = P.KEEN_OBSERVER + P.TWIN_FANGS;
  const TRAIT_ELEMENTALIST_CRITICAL_CHANCE = P.SUPERIOR_ELEMENTS * P.WEAKNESS;
  const TRAIT_MESMER_CRITICAL_CHANCE = P.DANGER_TIME * P.SLOW;
  const TRAIT_NECROMANCER_CRITICAL_CHANCE = P.DEATH_PERCEPTION + P
    .DECIMATE_DEFENSES * P.VULNERABILITY + P.TARGET_THE_WEAK;
  const TRAIT_GUARDIAN_CRITICAL_CHANCE = P.RADIANT_POWER * P.BURNING + P
    .RIGHTEOUS_INSTINCTS * P.RETALIATION;
  let CRITICAL_CHANCE = 5 + (PRECISION - 1000) / 21 + BUFF + SIGIL_OF_ACCURACY +
    TRAIT_ENGINEER_CRITICAL_CHANCE + TRAIT_RANGER_CRITICAL_CHANCE +
    TRAIT_THIEF_CRITICAL_CHANCE + TRAIT_ELEMENTALIST_CRITICAL_CHANCE +
    TRAIT_MESMER_CRITICAL_CHANCE + TRAIT_NECROMANCER_CRITICAL_CHANCE +
    TRAIT_GUARDIAN_CRITICAL_CHANCE + P.BRUTAL_MOMENTUM + P.UNSUSPECTING_FOE;
  if (P.BURST_PRECISION === 1 || P.HIDDEN_KILLER === 1 || P.PRECISE_STRIKE ===
    1 || P.SUPERIOR_SIGIL_OF_VISION === 1) {
    CRITICAL_CHANCE = 100;
  }
  demoStart(parseFloat(document.getElementById('P.CRITICAL_CHANCE').innerText
    .substring(0, document.getElementById('P.CRITICAL_CHANCE').innerText
      .length - 2)), 2, '', ' %', 'P.CRITICAL_CHANCE', CRITICAL_CHANCE.toFixed(2
  ));
}
